import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";

const fredoka = Fredoka({
    subsets: ["latin"],
    variable: "--font-fredoka",
    weight: ["400", "500", "700"], // du velger hvor tykk du vil ha den 😄
});

export const metadata: Metadata = {
    title: "Sol ute, sol inne.....",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='no' className={fredoka.variable}>
            <body className='font-sans antialiased'>{children}</body>
        </html>
    );
}
