name: Daily Supabase Ping

on:
    schedule:
        - cron: "0 6 * * *"
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping Supabase RSVP-tabellen
              run: |
                  curl -s \
                    -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
                    "https://zzodfsbtdfkjcepvngyu.supabase.co/rest/v1/rsvp?select=id"
