name: A ping in the side...

on:
    schedule:
        - cron: "*/45 * * * *"
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping Supabase via public table
              env:
                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
              run: |
                  echo "☁️ Vekker Supabase med et lite nuss..."
                  curl -s \
                    -H "apikey: $SUPABASE_ANON_KEY" \
                    "https://jqwyylgvmzicrcfjhuit.supabase.co/rest/v1/solverktoy?select=id"
